#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_border                off
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       stack # bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   5
yabai -m space --layout bsp
yabai -m config debug_output on

# manage=off
yabai -m rule --add app="^Karabiner" manage=off

yabai -m rule --add app=PyCharm manage=off
yabai -m rule --add app=RubyMine manage=off
yabai -m rule --add app=GoLand manage=off
yabai -m rule --add app="JetBrains Toolbox" manage=off

yabai -m rule --add label="アクティビティモニタ" app="^アクティビティモニタ$" manage=off
yabai -m rule --add label="キーチェーンアクセス" app="^キーチェーンアクセス$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" manage=off
yabai -m rule --add label="システム環境設定" app="^システム環境設定$" manage=off
yabai -m rule --add app="^システム情報$" manage=off
yabai -m rule --add label="Alfred" app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Cold Turkey Blocker" manage=off
yabai -m rule --add app="^DeepL" manage=off

# space 1
yabai -m rule --add app="^kitty$" space=1 manage=on
yabai -m rule --add app="^Code$" space=1 manage=on
yabai -m space 1 --layout stack

# space 2
yabai -m rule --add app="^Google Chrome$" space=2 manage=on
yabai -m space 2 --layout bsp

# space 4
yabai -m rule --add app="^Fantastical$" space=4 manage=on
yabai -m rule --add app="^Craft$" space=4 manage=on
yabai -m space 4 --layout stack

# space 5
yabai -m rule --add app="^Toggl Track$" space=5 manage=on
yabai -m rule --add app="^Cron$" space=5 manage=on
yabai -m rule --add app="^Habitify$" space=5 manage=on
yabai -m rule --add app="^Tot$" space=5 manage=on
yabai -m space 5 --layout bsp --balance

# space 6
yabai -m rule --add app="^Spotify$" space=6 manage=on
yabai -m space 6 --layout bsp --balance

# space 7
yabai -m rule --add app="Slack" space=7 manage=on
yabai -m rule --add app="Discord" space=7 manage=on
yabai -m rule --add app="Mimestream" space=7 manage=on
yabai -m space 7 --layout stack

echo "yabai configuration loaded.."
