#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        focused        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                off            \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  5              \
    bottom_padding               5              \
    left_padding                 5              \
    right_padding                5              \
    window_gap                   5              \
    layout                       stack          \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m space --layout bsp
yabai -m config debug_output on

yabai -m rule --add app="Finder" sticky=on
yabai -m rule --add app="(AS TimerPRO|1Password|そら案内)" sticky=on layer=above

# manage=off
yabai -m rule --add app="^Karabiner.*" manage=off
yabai -m rule --add app="(App Store|Bartender.*)" manage=off
yabai -m rule --add app="BetterDisplay" manage=off
yabai -m rule --add app="(JetBrains Toolbox|GoLand|RubyMine|PyCharm|WebStorm)" manage=off
yabai -m rule --add app="(Cold Turkey Blocker|Contexts|DeepL|Finder|CotEditor|Rewind)" manage=off
yabai -m rule --add app="(Avid Link|Creative Cloud)" manage=off
yabai -m rule --add app="(Dictionaries|そら案内)" manage=off
yabai -m rule --add app="(LINE)" manage=off
yabai -m rule --add app="(System Settings|System Information|Activity Monitor|Keychain Access)" manage=off

# space 1
yabai -m rule --add app="(kitty|Code)" space=^1
yabai -m space 1 --layout stack --padding abs:0:0:0:0 --gap abs:0

# space 2
yabai -m space 2 --layout bsp

# space 3
yabai -m rule --add app="(Roam Research|Dictionaries|Papers)" space=^3

# space 4
yabai -m rule --add app="(Fantastical)" space=^4
yabai -m space 4 --layout stack

# space 5
yabai -m rule --add app="(Sunsama|Toggl Track)" space=^5
yabai -m rule --add app="Sunsama" grid=1:9:3:0:6:1 # 1x8 grid (right 6 columns)
yabai -m rule --add app="Toggl Track" grid=1:9:0:0:3:1 # 1x8 grid (left 3 columns)
yabai -m space 5 --layout float

# space 6
yabai -m rule --add app="(Spotify)" space=^6
yabai -m space 6 --layout stack

# space 7
yabai -m rule --add app="(Slack|Discord|Mimestream|LINE)" space=^7
yabai -m space 7 --layout stack 

# space 8
yabai -m rule --add app="(ClickUp|Mem|Obsidian)" space=^8
yabai -m space 8 --layout stack

echo "yabai configuration loaded.."
