[tools]
# languages
ruby = "3.4.3"
bun = "1.2.16"
node = "24.2.0"
python = "3.11"

# tools
usage = "latest"
hk = "latest"
aube = "latest"

# npm packages
claude-code = "latest"
"npm:ccusage" = "latest"
"npm:prettier" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
