[tools]
# languages
ruby = "3.4.3"
bun = "1.2.16"
node = "24.2.0"
python = "latest"

# tools
usage = "latest"
hk = "latest"

# npm packages
"npm:@anthropic-ai/claude-code" = "latest"
"npm:ccusage" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
